### PR TITLE
convert to url path instead of org

### PR DESCRIPTION
**Pull request by gaieges**
Allows it to be usable in other places other than just okta.

### CODE REVIEW

**Comment by jpf** [comment]
Hi Evin, 

Thanks for the patch! This project inspired me to write [lokey](https://github.com/jpf/lokey), a more comprehensive tool to convert between all sorts of key formats.

With lokey, you can do the following: 

`$ lokey fetch jwk login.salesforce.com | lokey to pem`

More examples are available on a StackOverflow answer here: https://stackoverflow.com/a/43104608

My question for you is: Does this use of lokey meet your needs? I'm hoping for lokey to solve all common RSA key conversion use cases.

**Comment by gaieges** [comment]
I didn't get too deep into it, but on first glance, that tool is an awesome idea! Gave ya a star :)

However - from the looks of it, it looks like you're still making some assumptions about where the jwks is, right?  I think that's helpful in generic cases, but if you're messing with the jwks, you probably know where it ilves, right?  

Is there a way to override and pass it a direct json url? 

My use case right now is cognito - their Url's look like this: 

`https://cognito-idp.eu-central-1.amazonaws.com/<region-id>_<pool-id>/.well-known/jwks.json`

**Comment by jpf** [comment]
Ah! A new use-case! Thanks for the example. I used domain name since, at the time, I thought that all JWKS data would be referenced via `/.well-known/openid-configuration' since that what Okta, Google, and Salesforce were doing at the time. That assumption is encoded here: https://github.com/jpf/lokey/blob/master/lokey/__init__.py#L242-L243

I like the simplicity of just giving a domain name, but given your use case, I think what I'll do is assume that the input is a JWKS URI if the input string starts with "http" – would that work for you?

**Comment by gaieges** [comment]
I think that would, yeah!  Implies that your users need to make sure they dont copy and paste and include the `http` when using your previous approach.

**Comment by jpf** [comment]
Ah, good point about copy-and-paste. I'll think that over but hope to have an update to lokey out by the end of this week. Thanks for the feedback.

**Comment by gaieges** [comment]
Can prob close this, no?

**Pull request closed without merging**
